# Generated by Django 3.2.6 on 2021-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(blank=True, choices=[('sedan', 'sedan'), ('suv', 'suv'), ('wagon', 'wagon'), ('wagon', 'wagon'), ('coup', 'coup'), ('hatchback', 'hatchbak'), ('pickup', 'pickup'), ('compact', 'compact'), ('compact', 'compact'), ('sport coupe', 'sport coupe'), ('van', 'van'), ('crossover', 'crossover')], max_length=15)),
                ('title', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, choices=[('red', 'red'), ('yellow', 'yellow'), ('orange', 'orange'), ('green', 'green'), ('blue', 'blue'), ('violet', 'violet'), ('gray', 'gray'), ('white', 'white'), ('black', 'black')], max_length=10)),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'manual'), ('auto', 'auto'), ('robot', 'robot')], max_length=10)),
                ('rul', models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right')], max_length=10)),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
