# Generated by Django 3.2.6 on 2021-08-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
