# Generated by Django 3.2.6 on 2021-08-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='car',
            name='release_date',
            field=models.DateField(max_length=4),
        ),
    ]
